# -*- coding: utf-8 -*-
"""JSON Refiner Advanced Edition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_4qyyZZdLPWxZ5WXbCOTXtN9Bbmi5RT
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

messages = [
    {"role": "user", "content": "Who are you?"}
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM. from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
     {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
add_generation_prompt=True,
tokenize=True,
return_dict=True,
return_tensors="pt",
).to (model. device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio json5 jsonschema python-dotenv pydantic

import gradio as gr
import json
import json5
from jsonschema import ValidationError

# ==============================
# JSON Refiner Core
# ==============================

class JSONRefiner:

    def __init__(self, remove_null=False, sort_keys=False, indent=2, minify=False):
        self.remove_null = remove_null
        self.sort_keys = sort_keys
        self.indent = None if minify else indent

    def parse_json(self, text):

        if not text.strip():
            raise ValueError("Input JSON is empty")

        try:
            return json.loads(text)

        except Exception:
            try:
                return json5.loads(text)
            except Exception as e:
                raise ValueError(f"Invalid JSON: {str(e)}")

    def clean(self, obj):

        if isinstance(obj, list):
            return [self.clean(i) for i in obj]

        if isinstance(obj, dict):

            keys = sorted(obj.keys()) if self.sort_keys else obj.keys()
            new_obj = {}

            for k in keys:

                v = self.clean(obj[k])

                if self.remove_null and v is None:
                    continue

                new_obj[k] = v

            return new_obj

        return obj

    def refine(self, text):

        data = self.parse_json(text)
        data = self.clean(data)

        return json.dumps(data, indent=self.indent)


# ==============================
# Processing Function
# ==============================

def refine_json(input_json, remove_null, sort_keys, minify):

    try:

        refiner = JSONRefiner(
            remove_null=remove_null,
            sort_keys=sort_keys,
            minify=minify
        )

        result = refiner.refine(input_json)

        return "✅ JSON processed successfully", result

    except Exception as e:

        return f"❌ Error: {str(e)}", ""


# ==============================
# Gradio UI
# ==============================

with gr.Blocks(title="JSON Refiner Advanced") as app:

    gr.Markdown("## 🧰 JSON Refiner – Advanced Tool")

    with gr.Row():

        input_json = gr.Textbox(
            label="Input JSON",
            lines=15,
            placeholder="Paste your JSON here..."
        )

        output = gr.Textbox(
            label="Refined JSON",
            lines=15
        )

    with gr.Row():

        remove_null = gr.Checkbox(label="Remove Null Values")
        sort_keys = gr.Checkbox(label="Sort Keys Alphabetically")
        minify = gr.Checkbox(label="Minify JSON")

    run_btn = gr.Button("🚀 Refine JSON")

    status = gr.Textbox(label="Status")

    run_btn.click(
        refine_json,
        inputs=[input_json, remove_null, sort_keys, minify],
        outputs=[status, output]
    )

app.launch()